export default {
    "1-synchronized-identities": "7.1 - Synchronized Identities",
    "2-prepare-for-synchronization": "7.2 - Prepare for Synchronization",
    "3-idfix": "7.3 - IdFix",
    "4-configuring-synchronization": "7.4 - Configuring Synchronization",
    "5-hybrid-identities-authentication-options": "7.5 - Hybrid Identities Authentication Options",
    "6-contacts": "7.6 - Contacts",
    "7-service-health": "7.7 - Service Health",
    "8-message-center": "7.8 - Message Center",
    "9-adoption-score": "7.9 - Adoption Score",
    "10-troubleshooting-tools": "7.10 - Troubleshooting Tools",
    "11-auditing": "7.11 - Auditing",
    "12-information-security": "7.12 - Information Security",
    "13-microsoft-purview": "7.13 - Microsoft Purview",
    "14-data-classification": "7.14 - Data Classification",
    "15-data-connectors": "7.15 - Data Connectors",
    "16-alert-policies-roles-and-scopes": "7.16 - Alert Policies Roles and Scopes",
    "17-compliance-solutions": "7.17 - Compliance Solutions",
    "18-data-loss-prevention": "7.18 - Data Loss Prevention"
}