export default {
    "chapter8-introduction-to-storage-accounts": "Chapter 8 - Introduction to Storage Accounts",
    "chapter8.2-storage-comparison": "Chapter 8.2 - Storage Comparison",
    "chapter8.3-core-storage-services": "Chapter 8.3 - Core Storage Services",
    "chapter8.4-performance-tiers": "Chapter 8.4 - Performance Tiers",
    "chapter8.5-access-tiers": "Chapter 8.5 - Access Tiers",
    "chapter8.6-replication-data-redundancy": "Chapter 8.6 - Replication Data Redundancy",
    "chapter8.7-LRS-ZRS": "Chapter 8.7 - LRS ZRS",
    "chapter8.8-GRS-GZRS": "Chapter 8.8 - GRS GZRS",
    "chapter8.9-ra-grs-ra-gzrs": "Chapter 8.9 - RA-GRS RA-GZRS",
    "chapter8.10-introduction-to-azure-blob": "Chapter 8.10 - Introduction to Azure Blob",
    "chapter8.11-azure-blob-types": "Chapter 8.11 - Azure Blob Types",
    "chapter8.12-azure-blob-moving-data": "Chapter 8.12 - Azure Blob Moving Data",
    "chapter8.13-introduction-to-azure-files": "Chapter 8.13 - Introduction to Azure Files",
    "chapter8.14-azure-files-use-cases": "Chapter 8.14 - Azure Files Use Cases",
    "chapter8.15-azure-files-feature": "Chapter 8.15 - Azure Files Feature",
    "chapter8.16-azure-file-sync": "Chapter 8.16 - Azure File Sync",
    "chapter8.17-azure-storage-explorer": "Chapter 8.17 - Azure Storage Explorer",
    "chapter8.18-azcopy": "Chapter 8.18 - AzCopy",
    "chapter8.19-azure-import-export-service": "Chapter 8.19 - Azure Import Export Service",
    "chapter8.20-sas": "Chapter 8.20 - SAS",
    "chapter8.21-storage-accounts-cheatsheet": "Chapter 8.21 - Storage Accounts CheatSheet"
}